version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
  
  random-restaurant-api:
    build: ./random-restaurant-api
    ports: 
      - 8080:8080
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo_db:27017
      MONGODB_ENV: docker
    depends_on:
      - mongo_db
    volumes:
      - random-restaurant-api:/data/api

  random-restaurant-web:
    build: ./random-restaurant-web
    ports: 
      - 3000:3000
    depends_on:
      - random-restaurant-api

volumes:
  mongo_db: 
    name: "restaurant-data"
  random-restaurant-api:
    name: "api-logs"
  